server:
  port: 8000

spring:
  application:
    name: log-service
  cloud:
    nacos:
      config:
        serverAddr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'
  config:
    import:
      - nacos:nacos-config-example.properties?refreshEnabled=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug
